CREATE TABLE IF NOT EXISTS ROLE
(
ROLEID INTEGER PRIMARY KEY AUTO_INCREMENT,
ROLENAME VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER
( 
USEREMAIL VARCHAR(100) PRIMARY KEY,
PASSWORD VARCHAR(20) NOT NULL,
FNAME VARCHAR(40) NOT NULL,
LNAME VARCHAR(40) NOT NULL,
ROLEID INTEGER NOT NULL,
FOREIGN KEY (ROLEID) REFERENCES ROLE(ROLEID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS SPECIES
(
SPECIESID INTEGER PRIMARY KEY AUTO_INCREMENT,
SPECIESNAME VARCHAR(40) NOT NULL UNIQUE,
SPECIESLATINNAME VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS LOCATION
(
LOCATIONID INTEGER PRIMARY KEY AUTO_INCREMENT,
LOCATIONNAME VARCHAR(40) NOT NULL UNIQUE,
COUNTY VARCHAR(40) 
);

CREATE TABLE IF NOT EXISTS UPLOAD
(
UPLOADID INTEGER PRIMARY KEY AUTO_INCREMENT,
UPLOADNAME VARCHAR(40) NOT NULL,
UPLOADDATE DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS SIGHTING
(
SIGHTINGID VARCHAR(20) PRIMARY KEY,
SPECIESID INTEGER NOT NULL,
LOCATIONID INTEGER NOT NULL,
DATE_TIME VARCHAR(40) NOT NULL,
UPLOADID INTEGER NOT NULL,
-- FOREIGN KEY (UPLOADID) REFERENCES UPLOAD(UPLOADID),
FOREIGN KEY (SPECIESID) REFERENCES SPECIES(SPECIESID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (LOCATIONID) REFERENCES LOCATION(LOCATIONID) ON DELETE CASCADE ON UPDATE CASCADE 
);