SELECT * FROM IMPORTEDDATA;
SELECT * FROM LOCATION;
SELECT * FROM SIGHTING;
SELECT * FROM SPECIES;
SELECT * FROM LOGIN;

ALTER TABLE IMPORTEDDATA MODIFY COLUMN ID VARCHAR(255);
ALTER TABLE IMPORTEDDATA CHANGE COLUMN `DATE` `DATE_TIME` VARCHAR(40);
ALTER TABLE IMPORTEDDATA MODIFY COLUMN LOCATION VARCHAR(40);
ALTER TABLE IMPORTEDDATA MODIFY COLUMN SPECIES VARCHAR(40);
ALTER TABLE IMPORTEDDATA MODIFY COLUMN LATINNAME VARCHAR(40);

-- INSERTING UNIQUE DATA INTO SPECIES AND LOCATION
INSERT IGNORE INTO SPECIES (SPECIESNAME, SPECIESLATINNAME)
SELECT SPECIES, LATINNAME
FROM IMPORTEDDATA;

INSERT IGNORE INTO LOCATION (LOCATIONNAME)
SELECT LOCATION
FROM IMPORTEDDATA;

-- INSERTING INTO SIGHTING WHERE ID IS CORRECT LENGTH AND DATE/TIME IS VALID - USING ID'S INSTEAD OF NAMES
INSERT INTO SIGHTING (SIGHTINGID, SPECIESID, LOCATIONID, DATE_TIME, UPLOADID)
SELECT I.ID, S.SPECIESID, L.LOCATIONID, I.DATE_TIME, 1
FROM IMPORTEDDATA I 
JOIN SPECIES S ON I.SPECIES = S.SPECIESNAME
JOIN LOCATION L ON I.LOCATION = L.LOCATIONNAME
WHERE (LENGTH(I.ID) = 20) 
AND STR_TO_DATE(I.DATE_TIME, '%Y-%m-%dT%H:%i:%s') IS NOT NULL;

-- DATA THAT WASN'T ENTERED INTO SIGHTING DUE TO ERRORS IN DATA
SELECT * FROM IMPORTEDDATA I
WHERE NOT EXISTS (
    SELECT 1 
    FROM SIGHTING S 
    WHERE S.SIGHTINGID = I.ID
);

-- SELECT ALL WHERE DATE_TIME IS NOT VALID
SELECT * FROM IMPORTEDDATA
WHERE STR_TO_DATE(DATE_TIME, '%Y-%m-%dT%H:%i:%s') IS NULL;